import type { RestaurantId } from "@/ptero/config/canteen/restaurants";

/** Meal periods — same labels as CUHK UC canteen for merge compatibility. */
export type MealPeriod = "breakfast" | "lunch" | "tea" | "dinner";

export const PLACEHOLDER_IMAGE = "https://via.placeholder.com/200";

export type CanteenMenuItem = {
  id: string;
  name: string;
  description?: string;
  price: number;
  category: string;
  imageUrl: string;
  timeZones: MealPeriod[];
};

export const MEAL_PERIODS: Record<
  MealPeriod,
  { label: string; order: number }
> = {
  breakfast: { label: "Breakfast", order: 0 },
  lunch: { label: "Lunch", order: 1 },
  tea: { label: "Tea Time", order: 2 },
  dinner: { label: "Dinner", order: 3 },
};

const B: MealPeriod[] = ["breakfast"];
const L: MealPeriod[] = ["lunch"];
const T: MealPeriod[] = ["tea"];
const D: MealPeriod[] = ["dinner"];
const LD: MealPeriod[] = ["lunch", "dinner"];
const ALL: MealPeriod[] = ["breakfast", "lunch", "tea", "dinner"];
const LTD: MealPeriod[] = ["lunch", "tea", "dinner"];

function item(
  partial: Omit<CanteenMenuItem, "imageUrl"> & { imageUrl?: string },
): CanteenMenuItem {
  return { imageUrl: PLACEHOLDER_IMAGE, ...partial };
}

/** CityU canteen menus — City Express from Order.Place; Ebeneezer's from 5380 board. */
const MENUS: Record<RestaurantId, CanteenMenuItem[]> = {
  "city-express-ac1": [
    item({
      id: "spicy-pork-diced-mapo-tofu-rice-with-kumquat-salted-lemon-7-up",
      name: "Spicy Pork Diced Mapo Tofu Rice with Kumquat Salted Lemon 7-Up (香辣肉丁麻婆豆腐飯 · 金桔鹹檸七喜)",
      description: "包含飲料",
      price: 36,
      category: "Back to School Offers",
      timeZones: ALL,
    }),
    item({
      id: "spicy-pork-diced-mapo-tofu-rice-with-hot-drink-upgrade-to-co-c387aa",
      name: "Spicy Pork Diced Mapo Tofu Rice with Hot Drink (Upgrade to cold drink +$1.5) (香辣肉丁麻婆豆腐飯 · 熱飲 · 轉凍飲品+$1.5)",
      description: "熱飲可加$1.5轉凍飲",
      price: 36,
      category: "Back to School Offers",
      timeZones: ALL,
    }),
    item({
      id: "sour-and-spicy-rice-noodles",
      name: "Sour and Spicy Rice Noodles (酸辣米線)",
      price: 22.5,
      category: "Sour and Spicy Rice Noodles",
      timeZones: ALL,
    }),
    item({
      id: "clear-soup-rice-noodles",
      name: "Clear Soup Rice Noodles (清湯米線)",
      price: 20.5,
      category: "Sour and Spicy Rice Noodles",
      timeZones: ALL,
    }),
    item({
      id: "thai-style-pratunam-chicken-rice-with-soup-of-the-day",
      name: "Thai-style Pratunam Chicken Rice with Soup of the Day (泰式水門雞飯 · 例湯)",
      price: 49.1,
      category: "Thai Savory Selections",
      timeZones: ALL,
    }),
    item({
      id: "lemongrass-chicken-leg-with-oil-rice",
      name: "Lemongrass Chicken Leg with Oil Rice (香茅雞髀 · 油飯)",
      price: 38.9,
      category: "Thai Savory Selections",
      timeZones: ALL,
    }),
    item({
      id: "duck-leg-noodle-soup",
      name: "Duck Leg Noodle Soup (鴨腿湯河粉)",
      price: 39,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "beef-double-combo-noodle-soup",
      name: "Beef Double Combo Noodle Soup (牛肉雙拼湯粉)",
      price: 39.9,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "lemongrass-chicken-wing-double-combo-noodle-soup",
      name: "Lemongrass Chicken Wing Double Combo Noodle Soup (香茅雞翼雙拼湯粉)",
      price: 35.8,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "lemongrass-pork-chop-double-combo-noodle-soup",
      name: "Lemongrass Pork Chop Double Combo Noodle Soup (香茅豬扒雙拼湯粉)",
      price: 35.8,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "lemongrass-chicken-wing-soup-noodles",
      name: "Lemongrass Chicken Wing Soup Noodles (香茅雞翼湯粉)",
      price: 35.8,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "fish-ball-soup-noodles",
      name: "Fish Ball Soup Noodles (魚蛋湯粉)",
      price: 29.7,
      category: "Thai Soup Noodles",
      timeZones: ALL,
    }),
    item({
      id: "salted-egg-three-treasures-rice",
      name: "Salted Egg Three Treasures Rice (鹹蛋三寶飯)",
      price: 32.7,
      category: "Roasted Meats",
      timeZones: ALL,
    }),
    item({
      id: "two-meat-roast-combo-rice",
      name: "Two Meat Roast Combo Rice (燒味雙拼飯)",
      price: 28.6,
      category: "Roasted Meats",
      timeZones: ALL,
    }),
    item({
      id: "single-meat-roast-rice",
      name: "Single Meat Roast Rice (燒味單拼飯)",
      price: 22,
      category: "Roasted Meats",
      timeZones: ALL,
    }),
    item({
      id: "spicy-pork-cubes-soy-sauce-chicken-rice",
      name: "Spicy Pork Cubes · Soy Sauce Chicken Rice (麻辣肉丁 · 豉油雞飯)",
      price: 44,
      category: "Roast Meat Recommendations",
      timeZones: ALL,
    }),
    item({
      id: "spicy-pork-cubes-roasted-duck-rice",
      name: "Spicy Pork Cubes · Roasted Duck Rice (麻辣肉丁 · 明爐燒鴨飯)",
      price: 44,
      category: "Roast Meat Recommendations",
      timeZones: ALL,
    }),
    item({
      id: "salted-egg-minced-pork-and-soy-sauce-chicken-leg-rice",
      name: "Salted Egg, Minced Pork, and Soy Sauce Chicken Leg Rice (鹹蛋 · 肉燥 · 油雞髀飯)",
      price: 43,
      category: "Roast Meat Recommendations",
      timeZones: ALL,
    }),
    item({
      id: "saliva-chicken-with-white-rice",
      name: "Saliva Chicken with White Rice (口水雞 · 白飯)",
      price: 40.9,
      category: "Roasted Meat Selections",
      timeZones: ALL,
    }),
    item({
      id: "simmered-pork-and-onsen-egg-donburi",
      name: "Simmered Pork and Onsen Egg Donburi (汁煮豚肉 · 溫泉玉子丼)",
      price: 49.1,
      category: "Donburi / Rice Bowls",
      timeZones: ALL,
    }),
    item({
      id: "spicy-beef-and-onsen-egg-donburi",
      name: "Spicy Beef and Onsen Egg Donburi (辣味牛肉 · 溫泉玉子丼)",
      price: 49.1,
      category: "Donburi / Rice Bowls",
      timeZones: ALL,
    }),
    item({
      id: "chikuwa-japanese-beef-sukiyaki-hot-pot",
      name: "Chikuwa Japanese Beef Sukiyaki Hot Pot (竹輪日式牛肉壽喜火鍋)",
      price: 56.3,
      category: "Japanese Hot Pot for One",
      timeZones: ALL,
    }),
    item({
      id: "chikuwa-japanese-pork-sukiyaki-hot-pot",
      name: "Chikuwa Japanese Pork Sukiyaki Hot Pot (竹輪日式豚肉壽喜火鍋)",
      price: 56.3,
      category: "Japanese Hot Pot for One",
      timeZones: ALL,
    }),
    item({
      id: "jumbo-crab-stick-japanese-beef-sukiyaki-hot-pot",
      name: "Jumbo Crab Stick Japanese Beef Sukiyaki Hot Pot (珍寶蟹棒日式牛肉壽喜火鍋)",
      price: 56.3,
      category: "Japanese Hot Pot for One",
      timeZones: ALL,
    }),
    item({
      id: "jumbo-crab-stick-japanese-pork-sukiyaki-hot-pot",
      name: "Jumbo Crab Stick Japanese Pork Sukiyaki Hot Pot (珍寶蟹棒日式豚肉壽喜火鍋)",
      price: 56.3,
      category: "Japanese Hot Pot for One",
      timeZones: ALL,
    }),
    item({
      id: "beef-soup-udon",
      name: "Beef Soup Udon (牛肉湯烏冬)",
      price: 49.1,
      category: "Japanese Soup Udon",
      timeZones: ALL,
    }),
    item({
      id: "teriyaki-chicken-chop-udon",
      name: "Teriyaki Chicken Chop Udon (照燒雞扒烏冬)",
      price: 46,
      category: "Japanese Soup Udon",
      timeZones: ALL,
    }),
    item({
      id: "breaded-fish-fillet-burger-fries",
      name: "Breaded Fish Fillet Burger & Fries (吉列魚柳包 · 薯條)",
      description: "製作需時約 10-15分鐘",
      price: 38.9,
      category: "Burgers",
      timeZones: ALL,
    }),
    item({
      id: "beef-burger-fries",
      name: "Beef Burger & Fries (牛肉漢堡包 · 薯條)",
      description: "製作需時約 10-15分鐘",
      price: 38.9,
      category: "Burgers",
      timeZones: ALL,
    }),
    item({
      id: "cheese-chicken-burger",
      name: "Cheese Chicken Burger (芝士雞肉漢堡包)",
      price: 20.5,
      category: "Burgers",
      timeZones: ALL,
    }),
    item({
      id: "halal-braised-beans-and-mixed-vegetables",
      name: "Halal Braised Beans and Mixed Vegetables (清真燴豆雜菜)",
      description: "製作需時約 10-15分鐘 · Vegetarian",
      price: 38,
      category: "Halal Food Value Meals",
      timeZones: ALL,
    }),
    item({
      id: "halal-curry-chicken-with-white-rice",
      name: "Halal Curry Chicken with White Rice (清真咖喱雞 · 白飯)",
      description: "製作需時約 10-15分鐘",
      price: 47.1,
      category: "Halal Food",
      timeZones: ALL,
    }),
    item({
      id: "home-style-rice-3-choices",
      name: "Home-style Rice (3 choices) (家常飯(三款))",
      price: 32.5,
      category: "Home-style Meals",
      timeZones: ALL,
    }),
    item({
      id: "home-style-rice-2-choices",
      name: "Home-style Rice (2 choices) (家常飯(兩款))",
      price: 24.5,
      category: "Home-style Meals",
      timeZones: ALL,
    }),
    item({
      id: "large-iced-vanilla-latte-16oz",
      name: "Large Iced Vanilla Latte (16oz) (大凍雲呢拿鮮奶咖啡(16oz))",
      price: 33.8,
      category: "Coffee Lounge",
      timeZones: ALL,
    }),
    item({
      id: "large-iced-hazelnut-latte-16oz",
      name: "Large Iced Hazelnut Latte (16oz) (大凍榛子鮮奶咖啡(16oz))",
      price: 33.8,
      category: "Coffee Lounge",
      timeZones: ALL,
    }),
  ],
  "ac2-canteen": [
    item({
      id: "ac2-congee",
      name: "Century Egg Congee",
      price: 26,
      category: "Breakfast",
      timeZones: B,
    }),
    item({
      id: "ac2-chicken-rice",
      name: "Chicken Rice",
      price: 36,
      category: "Mains",
      timeZones: LD,
    }),
    item({
      id: "ac2-fish-burger",
      name: "Fried Fish Burger",
      price: 40,
      category: "Mains",
      timeZones: L,
    }),
    item({
      id: "ac2-lemon-tea",
      name: "Iced Lemon Tea",
      price: 16,
      category: "Drinks",
      timeZones: ALL,
    }),
    item({
      id: "ac2-toast-set",
      name: "Ham & Egg Toast",
      price: 30,
      category: "Tea Time",
      timeZones: T,
    }),
    item({
      id: "ac2-spaghetti",
      name: "Tomato Meat Sauce Spaghetti",
      price: 44,
      category: "Mains",
      timeZones: D,
    }),
  ],
  "ac3-bistro": [
    item({
      id: "ac3-eggs-benedict",
      name: "Eggs Benedict",
      price: 48,
      category: "Breakfast",
      timeZones: B,
    }),
    item({
      id: "ac3-fish-burger",
      name: "Fried Fish Burger",
      description: "Western-style with fries.",
      price: 55,
      category: "Mains",
      timeZones: LD,
    }),
    item({
      id: "ac3-caesar",
      name: "Chicken Caesar Salad",
      price: 46,
      category: "Mains",
      timeZones: LTD,
    }),
    item({
      id: "ac3-latte",
      name: "Café Latte",
      price: 28,
      category: "Drinks",
      timeZones: ALL,
    }),
    item({
      id: "ac3-milk-tea",
      name: "Milk Tea",
      price: 22,
      category: "Drinks",
      timeZones: ALL,
    }),
  ],
  "hall-canteen-klnt": [
    item({
      id: "klnt-chicken-rice",
      name: "Chicken Rice",
      price: 35,
      category: "Mains",
      timeZones: LD,
    }),
    item({
      id: "klnt-fish-burger",
      name: "Fried Fish Burger",
      price: 38,
      category: "Mains",
      timeZones: LTD,
    }),
    item({
      id: "klnt-sandwich",
      name: "Club Sandwich",
      price: 32,
      category: "Café",
      timeZones: B,
    }),
    item({
      id: "klnt-milk-tea",
      name: "Milk Tea",
      price: 16,
      category: "Drinks",
      timeZones: ALL,
    }),
    item({
      id: "klnt-ramen",
      name: "Instant Ramen Set",
      price: 28,
      category: "Mains",
      timeZones: T,
    }),
  ],
  "hall-canteen-mos": [
    item({
      id: "mos-chicken-rice",
      name: "Chicken Rice",
      price: 35,
      category: "Mains",
      timeZones: LD,
    }),
    item({
      id: "mos-fish-burger",
      name: "Fried Fish Burger",
      price: 38,
      category: "Mains",
      timeZones: L,
    }),
    item({
      id: "mos-milk-tea",
      name: "Milk Tea",
      price: 16,
      category: "Drinks",
      timeZones: ALL,
    }),
    item({
      id: "mos-pasta",
      name: "Creamy Pasta",
      price: 42,
      category: "Mains",
      timeZones: D,
    }),
    item({
      id: "mos-muffin",
      name: "Blueberry Muffin",
      price: 18,
      category: "Café",
      timeZones: B,
    }),
  ],
  "city-chinese": [
    item({
      id: "cc-har-gow",
      name: "Har Gow (Shrimp Dumplings)",
      price: 32,
      category: "Dim Sum",
      timeZones: ALL,
    }),
    item({
      id: "cc-siu-mai",
      name: "Siu Mai",
      price: 30,
      category: "Dim Sum",
      timeZones: ALL,
    }),
    item({
      id: "cc-char-siu",
      name: "Char Siu Rice",
      price: 48,
      category: "Mains",
      timeZones: ALL,
    }),
    item({
      id: "cc-chicken-rice",
      name: "Chicken Rice",
      price: 42,
      category: "Mains",
      timeZones: ALL,
    }),
    item({
      id: "cc-milk-tea",
      name: "Milk Tea",
      price: 18,
      category: "Drinks",
      timeZones: ALL,
    }),
    item({
      id: "cc-red-bean",
      name: "Red Bean Sweet Soup",
      price: 24,
      category: "Dessert",
      timeZones: ALL,
    }),
  ],
  "ebeneezers-5380": [
    item({
      id: "a1-donar-lamb-kebab",
      name: "Donar Lamb Kebab (羊肉沙威瑪)",
      description: "A1",
      price: 47.7,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a2-gyros-chicken-kebab",
      name: "Gyros Chicken Kebab (雞肉沙威瑪)",
      description: "A2",
      price: 45.6,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a3-chicken-tikka-kebab",
      name: "Chicken Tikka Kebab (烤雞沙威瑪)",
      description: "A3",
      price: 45.6,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a4-falafel-kebab",
      name: "Falafel Kebab (鷹嘴豆餅沙威瑪)",
      description: "A4 · Vegetarian",
      price: 42.5,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a5-meatball-kebab",
      name: "Meatball Kebab (肉丸沙威瑪)",
      description: "A5",
      price: 43.6,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a6-real-beef-kebab",
      name: "Real Beef Kebab (牛肉沙威瑪)",
      description: "A6",
      price: 49.8,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a7-chicken-bites-kebab",
      name: "Chicken Bites Kebab (脆雞沙威瑪)",
      description: "A7",
      price: 47,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a8-fish-kebab",
      name: "Fish Kebab (魚肉沙威瑪)",
      description: "A8",
      price: 45.6,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a9-chicken-shish-kebab",
      name: "Chicken Shish Kebab (雞肉串燒沙威瑪)",
      description: "A9",
      price: 44,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "a10-halloumi-cheese-kebab",
      name: "Halloumi Cheese Kebab (哈罗米芝士沙威瑪)",
      description: "A10 · Vegetarian",
      price: 42,
      category: "Kebabs (Shawarma)",
      timeZones: ALL,
    }),
    item({
      id: "b1-vegetable-biryani",
      name: "Vegetable Biryani (蔬菜炒飯)",
      description: "B1 · Vegetarian",
      price: 39.5,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "b2-chicken-biryani",
      name: "Chicken Biryani (雞肉炒飯)",
      description: "B2",
      price: 44,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "b3-fish-biryani",
      name: "Fish Biryani (魚肉炒飯)",
      description: "B3",
      price: 39.5,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "b4-chicken-tikka-biryani",
      name: "Chicken Tikka Biryani (烤雞炒飯)",
      description: "B4",
      price: 47,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "b5-meatball-biryani",
      name: "Meatball Biryani (肉丸炒飯)",
      description: "B5",
      price: 48,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "b6-chicken-bites-biryani",
      name: "Chicken Bites Biryani (脆雞炒飯)",
      description: "B6",
      price: 48,
      category: "Biryanis (Fried Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c1-vegetable-curry-rice",
      name: "Vegetable Curry with Rice (蔬菜咖喱飯)",
      description: "C1 · Vegetarian",
      price: 38.4,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c2-chicken-curry-rice",
      name: "Chicken Curry with Rice (雞肉咖喱飯)",
      description: "C2",
      price: 39.4,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c3-fish-curry-rice",
      name: "Fish Curry with Rice (魚肉咖喱飯)",
      description: "C3",
      price: 39.4,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c4-meatball-curry-rice",
      name: "Meatball Curry with Rice (肉丸咖喱飯)",
      description: "C4",
      price: 42.5,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c5-chana-masala-rice",
      name: "Chana Masala with Rice (鷹嘴豆咖喱飯)",
      description: "C5 · Vegetarian",
      price: 41,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c6-dal-makhani-rice",
      name: "Dal Makhani with Rice (黑豆咖喱飯)",
      description: "C6 · Vegetarian",
      price: 41,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "c7-chicken-bites-curry-rice",
      name: "Chicken Bites Curry with Rice (脆雞咖喱飯)",
      description: "C7",
      price: 45,
      category: "Curries (Served with Rice)",
      timeZones: ALL,
    }),
    item({
      id: "d1-garden-salad",
      name: "Garden Salad (田園沙律)",
      description: "D1 · Vegetarian",
      price: 27.5,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "d2-roast-chicken-salad",
      name: "Roast Chicken Salad (燒雞沙律)",
      description: "D2",
      price: 39.4,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "d3-roast-lamb-salad",
      name: "Roast Lamb Salad (燒羊沙律)",
      description: "D3",
      price: 47.7,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "d4-chicken-tikka-salad",
      name: "Chicken Tikka Salad (烤雞沙律)",
      description: "D4",
      price: 41.5,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "d5-real-beef-salad",
      name: "Real Beef Salad (牛肉沙律)",
      description: "D5",
      price: 49.8,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "d6-halloumi-cheese-salad",
      name: "Halloumi Cheese Salad (哈罗米芝士沙律)",
      description: "D6 · Vegetarian",
      price: 42,
      category: "Salads",
      timeZones: ALL,
    }),
    item({
      id: "e1-roast-chicken-rice",
      name: "Roast Chicken with Rice (燒雞配飯)",
      description: "E1",
      price: 39.4,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e1-roast-chicken-chips",
      name: "Roast Chicken with Chips (燒雞配薯條)",
      description: "E1",
      price: 45.6,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e2-roast-lamb-rice",
      name: "Roast Lamb with Rice (燒羊配飯)",
      description: "E2",
      price: 47.7,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e2-roast-lamb-chips",
      name: "Roast Lamb with Chips (燒羊配薯條)",
      description: "E2",
      price: 54,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e3-chicken-tikka-rice",
      name: "Chicken Tikka with Rice (烤雞配飯)",
      description: "E3",
      price: 40.4,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e3-chicken-tikka-chips",
      name: "Chicken Tikka with Chips (烤雞配薯條)",
      description: "E3",
      price: 45.6,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e4-real-beef-rice",
      name: "Real Beef with Rice (牛肉配飯)",
      description: "E4",
      price: 49.8,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "e4-real-beef-chips",
      name: "Real Beef with Chips (牛肉配薯條)",
      description: "E4",
      price: 54.5,
      category: "Meat Lovers",
      timeZones: ALL,
    }),
    item({
      id: "f1-margherita",
      name: "Margherita Pizza (10 inch) (瑪格莉特薄餅)",
      description: "F1 · Vegetarian",
      price: 71.5,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f2-pepperoni",
      name: "Pepperoni Pizza (10 inch) (意式辣肉腸薄餅)",
      description: "F2",
      price: 77,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f3-supreme",
      name: "Supreme Pizza (10 inch) (至尊薄餅)",
      description: "F3",
      price: 83.5,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f4-chicken-tikka-pizza",
      name: "Chicken Tikka Pizza (10 inch) (烤雞薄餅)",
      description: "F4",
      price: 83.5,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f5-vegetarian-pizza",
      name: "Vegetarian Pizza (10 inch) (素食薄餅)",
      description: "F5 · Vegetarian",
      price: 77,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f6-hawaiian",
      name: "Hawaiian Pizza (10 inch) (夏威夷薄餅)",
      description: "F6",
      price: 77,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f7-chicken-express",
      name: "Chicken Express Pizza (10 inch) (雞肉特快薄餅)",
      description: "F7",
      price: 83.5,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "f8-turkey-ham-mushroom",
      name: "Turkey Ham & Mushroom Pizza (10 inch) (火雞火腿蘑菇薄餅)",
      description: "F8",
      price: 77,
      category: "Pizzas (10 inch)",
      timeZones: ALL,
    }),
    item({
      id: "g1-chips",
      name: "Chips (薯條)",
      description: "G1 · Vegetarian",
      price: 30,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "g2-samosas",
      name: "Samosas (2 pcs) (咖喱角（2件）)",
      description: "G2 · Vegetarian",
      price: 19.2,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "g3-falafels",
      name: "Falafels (3 pcs) (鷹嘴豆餅（3件）)",
      description: "G3 · Vegetarian",
      price: 20.7,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "g4-spring-rolls",
      name: "Spring Rolls (4 pcs) (春卷（4件）)",
      description: "G4 · Vegetarian",
      price: 20.7,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "g5-hummus-pita",
      name: "Hummus & Pita Bread (1 pc) (鷹嘴豆泥配皮塔餅)",
      description: "G5 · Vegetarian",
      price: 28,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "g6-gulab-jamun",
      name: "Gulab Jamun (each) (印式甜品（每件）)",
      description: "G6 · Vegetarian",
      price: 9,
      category: "Side Orders",
      timeZones: ALL,
    }),
    item({
      id: "drink-pepsi",
      name: "Pepsi (canned) (百事可樂（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-pepsi-light",
      name: "Pepsi Light (canned) (百事健怡（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-7up",
      name: "7 Up (canned) (七喜（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-7up-light",
      name: "7 Up Light (canned) (七喜健怡（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-mirinda",
      name: "Mirinda Orange (canned) (美年達橙汁（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-mountain-dew",
      name: "Mountain Dew (canned) (激浪（罐裝）)",
      description: "Vegetarian",
      price: 8.8,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-sirma-apple",
      name: "Sirma Vitamin Drink — Apple",
      description: "Vegetarian",
      price: 12.4,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-sirma-lemon",
      name: "Sirma Vitamin Drink — Lemon",
      description: "Vegetarian",
      price: 12.4,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-sirma-pomegranate",
      name: "Sirma Vitamin Drink — Pomegranate",
      description: "Vegetarian",
      price: 12.4,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-sirma-orange",
      name: "Sirma Vitamin Drink — Orange",
      description: "Vegetarian",
      price: 12.4,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-masala-tea",
      name: "Masala Tea (馬莎拉茶)",
      description: "Vegetarian",
      price: 12,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-cold-lemon-tea",
      name: "Cold Lemon Tea (凍檸檬茶)",
      description: "Vegetarian",
      price: 13.5,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-cold-green-tea",
      name: "Cold Green Tea (凍綠茶)",
      description: "Vegetarian",
      price: 13.5,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-mango-milk",
      name: "Mango Milk (芒果奶)",
      description: "Vegetarian",
      price: 13.5,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-coconut-milk",
      name: "Coconut Milk (椰奶)",
      description: "Vegetarian",
      price: 13.5,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "drink-coconut-water",
      name: "Coconut Water (椰子水)",
      description: "Vegetarian",
      price: 13.5,
      category: "Beverages",
      timeZones: ALL,
    }),
    item({
      id: "upgrade-soft-drink",
      name: "Upgrade Combo — Soft Drink",
      description: "Add to any main item · Vegetarian",
      price: 7,
      category: "Upgrade Combos",
      timeZones: ALL,
    }),
    item({
      id: "upgrade-tea",
      name: "Upgrade Combo — Tea",
      description: "Add to any main item · Vegetarian",
      price: 8,
      category: "Upgrade Combos",
      timeZones: ALL,
    }),
    item({
      id: "upgrade-samosa",
      name: "Upgrade Combo — 1pc Samosa",
      description: "Add to any main item · Vegetarian",
      price: 10,
      category: "Upgrade Combos",
      timeZones: ALL,
    }),
    item({
      id: "upgrade-spring-rolls",
      name: "Upgrade Combo — 2pcs Spring Roll",
      description: "Add to any main item · Vegetarian",
      price: 11,
      category: "Upgrade Combos",
      timeZones: ALL,
    }),
    item({
      id: "upgrade-falafel",
      name: "Upgrade Combo — 2pcs Falafel",
      description: "Add to any main item · Vegetarian",
      price: 14,
      category: "Upgrade Combos",
      timeZones: ALL,
    }),
    item({
      id: "addon-extra-cheese",
      name: "Extra Cheese",
      description: "Vegetarian",
      price: 19,
      category: "Add-ons",
      timeZones: ALL,
    }),
    item({
      id: "addon-extra-meat",
      name: "Extra Meat",
      price: 26.5,
      category: "Add-ons",
      timeZones: ALL,
    }),
  ]
};

export function getCanteenMenu(restaurantId: RestaurantId | string): CanteenMenuItem[] {
  return MENUS[restaurantId as RestaurantId] ?? [];
}

export function getCanteenMenuItem(
  restaurantId: string,
  itemId: string,
): CanteenMenuItem | undefined {
  return getCanteenMenu(restaurantId).find((i) => i.id === itemId);
}

export function groupMenuByMealPeriod(
  items: CanteenMenuItem[],
): { period: MealPeriod; label: string; items: CanteenMenuItem[] }[] {
  const periods = (Object.keys(MEAL_PERIODS) as MealPeriod[]).sort(
    (a, b) => MEAL_PERIODS[a].order - MEAL_PERIODS[b].order,
  );
  return periods
    .map((period) => ({
      period,
      label: MEAL_PERIODS[period].label,
      items: items.filter((i) => i.timeZones.includes(period)),
    }))
    .filter((g) => g.items.length > 0);
}

export function groupMenuByCategory(
  items: CanteenMenuItem[],
): { category: string; items: CanteenMenuItem[] }[] {
  const map = new Map<string, CanteenMenuItem[]>();
  for (const menuItem of items) {
    const list = map.get(menuItem.category) ?? [];
    list.push(menuItem);
    map.set(menuItem.category, list);
  }
  return [...map.entries()].map(([category, groupItems]) => ({
    category,
    items: groupItems,
  }));
}
