/**
 * Fetch the NA WebBites (Pin2Eat store 5500) dine-in menu.
 * One request, then 500ms before it so a rerun stays at 1 req / 500ms.
 *
 *   npx tsx scripts/scrape-na-webbites.ts
 *
 * Writes data/na-webbites.json and the storefront catalog
 * apps/web/src/data/canteen/na-webbites-menu.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const JSON_OUT = path.join(ROOT, "data", "na-webbites.json");
const TS_OUT = path.join(
  ROOT,
  "apps",
  "web",
  "src",
  "data",
  "canteen",
  "na-webbites-menu.ts",
);
const ENDPOINT =
  "https://meal.pin2eat.com/api/home/product-menus?store_id=5500&table_name=1&takeout=0&order_sub_type=0";
const GAP_MS = 500;

type MenuCategory = "mains" | "snacks" | "drinks" | "dessert";

type RawProduct = {
  product_id?: string;
  local_name?: string;
  en_name?: string;
  cn_name?: string;
  price?: string | number;
  cover_image?: string;
  status?: string;
  has_stock?: string | number;
  stock_number?: string | number;
  description?: {
    local_description?: string;
    en_description?: string;
    cn_description?: string;
  } | null;
};

type RawGroup = {
  group_id?: string;
  local_name?: string;
  en_name?: string;
  products?: RawProduct[];
};

type Dish = {
  id: string;
  name: string;
  nameZh?: string;
  price: number;
  category: string;
  sourceCategory: string;
  description?: string;
  image?: string;
  isAvailable: boolean;
  sourceId: "na-webbites";
  appCategory: MenuCategory;
};

type Skipped = {
  productId: string;
  sourceCategory: string;
  reason: string;
  localName: string;
  enName: string;
  price: string;
};

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function text(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function hasCjk(value: string): boolean {
  return /[\u3400-\u9fff]/.test(value);
}

function canonicalCategory(source: string): MenuCategory {
  const blob = source.toLowerCase();
  if (/甜品|dessert/.test(blob)) return "dessert";
  if (/零食|snack|外賣配套|utensil/.test(blob)) return "snacks";
  if (/飲|茶|奶|drink|tea|juice|咖啡|coffee/.test(blob)) return "drinks";
  return "mains";
}

function available(product: RawProduct): boolean {
  if (text(product.status) !== "1") return false;
  const stock = Number(product.has_stock);
  const count = Number(product.stock_number);
  if (stock === 1) return true;
  if (stock === -1) return true;
  if (stock === 0) return Number.isFinite(count) && count > 0;
  return false;
}

function parsePrice(raw: unknown): number | null {
  if (raw == null || raw === "") return null;
  const n = typeof raw === "number" ? raw : Number(String(raw).trim());
  if (!Number.isFinite(n)) return null;
  return Math.round(n * 100) / 100;
}

function descriptionOf(product: RawProduct): string {
  const d = product.description;
  if (!d) return "";
  return (
    text(d.local_description) ||
    text(d.en_description) ||
    text(d.cn_description)
  );
}

function tsString(value: string): string {
  return JSON.stringify(value);
}

function renderTs(items: Dish[]): string {
  const rows = items
    .map((item) => {
      const lines = [
        `    id: ${tsString(item.id)},`,
        `    name: ${tsString(item.name)},`,
      ];
      if (item.nameZh) lines.push(`    nameZh: ${tsString(item.nameZh)},`);
      if (item.description) {
        lines.push(`    description: ${tsString(item.description)},`);
      }
      lines.push(`    price: ${item.price},`);
      lines.push(`    category: ${tsString(item.appCategory)},`);
      lines.push(`    sourceCategory: ${tsString(item.sourceCategory)},`);
      lines.push(`    image: ${tsString(item.image ?? "")},`);
      if (!item.isAvailable) lines.push(`    isAvailable: false,`);
      return `  {\n${lines.join("\n")}\n  }`;
    })
    .join(",\n");

  return `import type { SimpleMenuItem } from "@/data/canteen/simple-menu";

/**
 * Generated by scripts/scrape-na-webbites.ts from Pin2Eat store 5500.
 * Category labels are the Pin2Eat group names. Do not rename them here.
 */
export const NA_WEBBITES_MENU: SimpleMenuItem[] = [
${rows},
];
`;
}

async function main() {
  await sleep(GAP_MS);
  const res = await fetch(ENDPOINT, {
    headers: {
      Accept: "application/json",
      "Store-id": "5500",
      langcode: "zh_HK",
      "User-Agent":
        "Mozilla/5.0 (compatible; GraceRunMenuScrape/1.0; +https://www.gracerun.fit)",
    },
  });
  if (!res.ok) {
    throw new Error(`Pin2Eat menu HTTP ${res.status}`);
  }
  const body = (await res.json()) as {
    code?: number;
    data?: { group?: RawGroup[] };
  };
  if (body.code !== 200 || !Array.isArray(body.data?.group)) {
    throw new Error("Pin2Eat menu payload missing data.group");
  }

  const items: Dish[] = [];
  const skipped: Skipped[] = [];
  const seen = new Set<string>();

  for (const group of body.data.group) {
    const sourceCategory =
      text(group.local_name) || text(group.en_name) || "Untitled";
    for (const product of group.products ?? []) {
      const productId = text(product.product_id);
      if (!productId || seen.has(productId)) continue;
      seen.add(productId);

      const localName = text(product.local_name);
      const enName = text(product.en_name);
      const cnName = text(product.cn_name);
      const chinese = localName || cnName;
      const english = enName;
      const name = english || chinese;
      const price = parsePrice(product.price);
      const reasons: string[] = [];
      if (!name) reasons.push("missing name");
      if (price == null) reasons.push("missing price");
      if (reasons.length > 0) {
        skipped.push({
          productId,
          sourceCategory,
          reason: reasons.join("; "),
          localName,
          enName,
          price: text(String(product.price ?? "")),
        });
        continue;
      }

      const nameZh = chinese || undefined;
      const description = descriptionOf(product);
      const image = text(product.cover_image);
      items.push({
        id: `p${productId}`,
        name,
        ...(nameZh ? { nameZh } : {}),
        price: price as number,
        category: sourceCategory,
        sourceCategory,
        ...(description ? { description } : {}),
        ...(image ? { image } : {}),
        isAvailable: available(product),
        sourceId: "na-webbites",
        appCategory: canonicalCategory(sourceCategory),
      });
    }
  }

  const byCategory = new Map<string, number>();
  for (const item of items) {
    byCategory.set(item.sourceCategory, (byCategory.get(item.sourceCategory) ?? 0) + 1);
  }

  const catalog = {
    sourceId: "na-webbites" as const,
    campus: "cuhk" as const,
    endpoint: ENDPOINT,
    fetchedAt: new Date().toISOString(),
    serviceTime: "08:00-20:00",
    hoursNote:
      "Pin2Eat business_schedule frequency was 0;1;3;2;4;5 and is not mapped to weekday names here. Published hours are daily 08:00-20:00.",
    itemCount: items.length,
    categories: [...byCategory.entries()].map(([name, count]) => ({
      name,
      count,
    })),
    skipped,
    items: items.map(({ appCategory: _appCategory, ...dish }) => dish),
  };

  mkdirSync(path.dirname(JSON_OUT), { recursive: true });
  writeFileSync(JSON_OUT, `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
  writeFileSync(TS_OUT, renderTs(items), "utf8");

  console.log(`wrote ${items.length} dishes to ${JSON_OUT}`);
  console.log(`wrote ${TS_OUT}`);
  console.log("categories:");
  for (const row of catalog.categories) {
    console.log(`  ${row.count}\t${row.name}`);
  }
  console.log(`skipped ${skipped.length}`);
  for (const row of skipped) {
    console.log(`  ${row.productId} ${row.reason} [${row.sourceCategory}]`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
